timezone: Europe/Dublin

logging:
  level: INFO

database:
  path: solar.db

dashboard:
  host: 0.0.0.0
  port: 8090
  actuals_to_forecast:
    pv1: 1
    pv2: 2

tariffs:
  periods:
    - effective_from: "2000-01-01"
      import:
        - days: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]
          start_time: "00:00"
          end_time: "08:00"
          rate: 0.2003
        - days: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]
          start_time: "08:00"
          end_time: "23:00"
          rate: 0.4062
        - days: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]
          start_time: "23:00"
          end_time: "24:00"
          rate: 0.2003
      export:
        - days: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]
          start_time: "00:00"
          end_time: "24:00"
          rate: 0.195

forecast:
  interval_seconds: 3600
  timeout_seconds: 10
  endpoint: https://api.forecast.solar/estimate
  arrays:
    - panel_id: 1
      name: East
      latitude: 53.4508401
      longitude: -6.15367
      declination: 35
      azimuth: -67.5
      peak_kw: 6.175
    - panel_id: 2
      name: West
      latitude: 53.4508401
      longitude: -6.15367
      declination: 35
      azimuth: 112.5
      peak_kw: 5.225

actuals:
  data_retrival_schedule:
    live_update_interval_seconds: 1
    full_updated_interval_seconds: 60
  modbus:
    host: 192.168.1.130
    port: 502
    timeout_seconds: 5
    default_device_id: 247
